language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
    packages:
      - boost
      - libgcrypt
      - libgpg-error
      - libopenmpi-dev
      - libmunge-dev
      - munge

script:
 - ./bootstrap && make build && cd build 
 - ../configure --with-test-rm=orte --with-test-ncore-per-CN=2 && make -j3
 - make -j3 check
