language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
    packages:
      - libelf-dev
      - libboost-dev
      - libmunge-dev
      - munge
      - libgcrypt11
      - libopenmpi-dev

script:
 - ./bootstrap && mkdir build && cd build 
 - ../configure --with-test-rm=orte --with-test-ncore-per-CN=2 && make -j3
 - make -j3 check
